title = "LNA-DEV Gallery"
languageCode = "en-us"
copyright = "🄯 CC-BY-SA Lukas Nagel"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Europe/Berlin"
theme = "github.com/LNA-DEV/hugo-theme-gallery"
timeout = "600s"

[params]
  title = "LNA-DEV Gallery"
  description = "Photography of Lukas Nagel / LNA-DEV"
  defaultTheme = "dark"
  [params.assets]
    faviconSvg = "https://lna-dev.net/assets/Ping%C3%BCino/Ping%C3%BCino.svg"
    faviconPng = "https://lna-dev.net/assets/Ping%C3%BCino/Ping%C3%BCino.svg"
    appleTouchIcon = "https://lna-dev.net/assets/Ping%C3%BCino/Ping%C3%BCino.svg"

[author]
  name = "Lukas Nagel"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 100
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    includeFields = ""

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
[[menu.footer]]
  name = "GitHub"
  url = "https://github.com/LNA-DEV"
  weight = 1
[[menu.footer]]
  name = "Website"
  url = "https://lna-dev.net"
  weight = 2
[[menu.footer]]
  name = "Archive"
  url = "/archive"
  weight = 3