name: HugoBuildDev

on:
  workflow_dispatch: # To have the ability to run the workflow manually

  push:
    branches: [dev]

env:
  NAME: ./
  CONTAINER-NAME: lna-dev-photo

jobs:
  ReleaseDEV:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install Hugo
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          extended: true

      # Build the hugo repository
      - run: hugo
        working-directory: ./${{ env.NAME }}/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: lnadev
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./${{ env.NAME }}/Dockerfile --tag lnadev/${{ env.CONTAINER-NAME }}:dev

      - name: Push the image to dockerhub
        run: docker push lnadev/${{ env.CONTAINER-NAME }}:dev